title: Nomaan Qureshi
author: Nomaan Qureshi
url: ""
baseurl: ""
favicon: "https://www.cmu.edu/favicon.ico"

markdown: kramdown
# ins_logo: "./hi.gif"
# ins_logo2: "../hi.gif"

tracking_id: UA-172754754-1

footer: yes
footer_url: "qureshinomaan.github.io"
footer_text: "Mohammad Nomaan Qureshi"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "research"
   link: "research"
 - name: "blog"
   link: "blog"


nav_blog:
 - name: "research"
   link: "research"
 - name: "blog"
   link: "blog"
