title: Nomaan Qureshi
author: Nomaan Qureshi
url: ""
baseurl: ""

markdown: kramdown
ins_logo: "./iiith_logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
